on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: firebase/hosting-deploy@v1
        with:
          project-id: bmi-controller
          firebase-token: ${{ secrets.FIREBASE_TOKEN }}
